<template>
    <table class="table table-striped table-hover">
        <tr>
            <th>Propiedades</th>
            <th>x</th>
            <th>x</th>
            <th>x</th>
        </tr>
        <tr>
            <td>Voltaje</td>
            <td></td>
            <td></td>
            <td></td>
        </tr>
        <tr>
            <td>Corriente</td>
            <td></td>
            <td></td>
            <td></td>
        </tr>
        <tr>
            <td>Caudal</td>
            <td></td>
            <td></td>
            <td></td>
        </tr>
    </table>
</template>